version: '2'

volumes:
    mayan_documents:
        external: false
    mayan_cache:
        external: false
    mayan_static:
        external: false
    mayan_settings:
        external: false
    database:
        external: false
    rabbit_data:
        external: false

services:
    postgres:
        env_file:
            - ./environment
        image: postgres
        volumes:
            - database:/var/lib/postgresql/data
    rabbitmq:
        env_file:
            - ./environment
        image: rabbitmq
        volumes:
            - rabbit_data:/var/lib/rabbitmq
    redis:
        image: redis
    nginx:
        depends_on:
        - frontend
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/conf/nginx/mayan-edms:/etc/nginx/conf.d/default.conf:ro
            - mayan_static:/tmp/mayan/static:ro
    frontend:
        build: .
        depends_on:
        - postgres
        - rabbitmq
        - redis
        env_file:
            - ./environment
        volumes:
            - mayan_documents:/usr/local/lib/python2.7/dist-packages/mayan/media/document_storage
            - mayan_cache:/usr/local/lib/python2.7/dist-packages/mayan/media/document_cache
            - mayan_static:/usr/local/lib/python2.7/dist-packages/mayan/media/static
            - mayan_settings:/usr/local/lib/python2.7/dist-packages/mayan/settings
    worker-fast:
        build: .
        depends_on:
        - postgres
        - rabbitmq
        - redis
        env_file:
            - ./environment
        environment:
            - MAYAN_ROLE=WORKER
            - MAYAN_WORKER_QUEUE=converter
        volumes:
            - mayan_documents:/usr/local/lib/python2.7/dist-packages/mayan/media/document_storage
            - mayan_cache:/usr/local/lib/python2.7/dist-packages/mayan/media/document_cache
            - mayan_settings:/usr/local/lib/python2.7/dist-packages/mayan/settings
    worker-medium:
        build: .
        depends_on:
        - postgres
        - rabbitmq
        - redis
        env_file:
            - ./environment
        environment:
            - MAYAN_ROLE=WORKER
            - MAYAN_WORKER_QUEUE=checkouts_periodic,documents_periodic,indexing,metadata,sources,sources_periodic,uploads
        volumes:
            - mayan_documents:/usr/local/lib/python2.7/dist-packages/mayan/media/document_storage
            - mayan_cache:/usr/local/lib/python2.7/dist-packages/mayan/media/document_cache
            - mayan_settings:/usr/local/lib/python2.7/dist-packages/mayan/settings
    worker-slow:
        build: .
        depends_on:
        - postgres
        - rabbitmq
        - redis
        env_file:
            - ./environment
        environment:
            - MAYAN_ROLE=WORKER
            - MAYAN_WORKER_QUEUE=mailing,ocr,tools,statistics
        volumes:
            - mayan_documents:/usr/local/lib/python2.7/dist-packages/mayan/media/document_storage
            - mayan_cache:/usr/local/lib/python2.7/dist-packages/mayan/media/document_cache
            - mayan_settings:/usr/local/lib/python2.7/dist-packages/mayan/settings
    beat:
        build: .
        depends_on:
        - postgres
        - rabbitmq
        - redis
        env_file:
            - ./environment
        environment:
            - MAYAN_ROLE=BEAT
        volumes:
            - mayan_settings:/usr/local/lib/python2.7/dist-packages/mayan/settings
